In [1]:
import pandas as pd
import numpy as np

In [3]:
results = pd.read_csv("results.csv")

In [4]:
results

,athlete,year,season,sport,discipline,pos,medal,country,country_code,team
0,1014,2020,Summer,Table Tennis,"Singles, Women",65.0,NaN,Nigeria,NGR,NaN
1,2069,2020,Summer,Archery,"Team, Mixed",24.0,NaN,Poland,POL,Sylwia Zyzańska
2,2069,2020,Summer,Archery,"Individual, Men",33.0,NaN,Poland,POL,NaN
3,11260,2020,Summer,Equestrian Jumping,"Individual, Open",5.0,NaN,Sweden,SWE,NaN
4,11260,2020,Summer,Equestrian Jumping,"Team, Open",1.0,Gold,Sweden,SWE,Sweden
...,...,...,...,...,...,...,...,...,...,...
291705,80232,1896,Summer,Shooting,"Free Rifle, Three Positions, 300 metres, Men",NaN,NaN,Greece,GRE,NaN
291706,80232,1896,Summer,Shooting,"Military Rifle, 200 metres, Men",11.0,NaN,Greece,GRE,NaN
291707,80233,1896,Summer,Shooting,"Military Rifle, 200 metres, Men",NaN,NaN,Great Britain,GBR,NaN
291708,80234,1896,Summer,Shooting,"Military Rifle, 200 metres, Men",NaN,NaN,Greece,GRE,NaN
291709,102578,1896,Summer,Shooting,"Free Rifle, Three Positions, 300 metres, Men",NaN,NaN,Greece,GRE,NaN

In [9]:
athletes = pd.read_csv(filepath_or_buffer="athletes.txt", sep=";")

In [11]:
merged = pd.merge(left = athletes, right = results, how="inner")

count      41913
unique         3
top       Bronze
freq       14092
Name: medal, dtype: object